### ISSUE TITLE
How to configure the conda environment？

### ISSUE THREAD

**Issue by Fengshihao1** [slothfulxtx/cxtrack3d#1]
Hello, author.
    Thank you so much for your work. I have a question for you：
    The cuda version I use is 10.2, and the pytorch version is 1.7. When configuring the pytorch3D library, it has been configured poorly. What is the reason for this, can you provide the dependent libraries of your code environment?

**Comment by slothfulxtx** [comment]
Hi, 
thanks for your interest! We adopt torch==1.8.0, cuda==11.1, and pytorch3d==0.6.2 for training and testing. Due to the limit of our GPU version(RTX 3090), we haven't evaluated our code on pytorch==1.7. I guess this modification has minor impact on the performance of our network. You can read [this](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) for more detailed instructions on how to configure pytorch3d on your server.
